USE [master]
GO

/****** Object:  Database [Scraper]    Script Date: 3/26/2018 9:23:15 PM ******/
CREATE DATABASE [Scraper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Scraper', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Scraper.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Scraper_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Scraper_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Scraper] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Scraper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Scraper] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Scraper] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Scraper] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Scraper] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Scraper] SET ARITHABORT OFF 
GO

ALTER DATABASE [Scraper] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Scraper] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Scraper] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Scraper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Scraper] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Scraper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Scraper] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Scraper] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Scraper] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Scraper] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Scraper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Scraper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Scraper] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Scraper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Scraper] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Scraper] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Scraper] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Scraper] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Scraper] SET  MULTI_USER 
GO

ALTER DATABASE [Scraper] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Scraper] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Scraper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Scraper] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Scraper] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Scraper] SET QUERY_STORE = OFF
GO

USE [Scraper]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Scraper] SET  READ_WRITE 
GO

